-- Create a compute pool for the containers
CREATE COMPUTE POOL IF NOT EXISTS SKILLPATHAI_POOL
  MIN_NODES = 1
  MAX_NODES = 3
  INSTANCE_FAMILY = CPU_X64_XS;

-- Create a service for the backend
CREATE SERVICE IF NOT EXISTS SKILLPATHAI_BACKEND
  IN COMPUTE POOL SKILLPATHAI_POOL
  SPECIFICATION_FILE = 'snowflake-container-config.yml'
  MIN_INSTANCES = 1
  MAX_INSTANCES = 3;

-- Create a service for the frontend
CREATE SERVICE IF NOT EXISTS SKILLPATHAI_FRONTEND
  IN COMPUTE POOL SKILLPATHAI_POOL
  SPECIFICATION_FILE = 'snowflake-container-config.yml'
  MIN_INSTANCES = 1
  MAX_INSTANCES = 3;

-- Start the services
ALTER SERVICE SKILLPATHAI_BACKEND RESUME;
ALTER SERVICE SKILLPATHAI_FRONTEND RESUME;

-- Get the service URLs
SELECT SYSTEM$GET_SERVICE_URL('SKILLPATHAI_BACKEND');
SELECT SYSTEM$GET_SERVICE_URL('SKILLPATHAI_FRONTEND'); 