{{ config(
    materialized='table',
    pre_hook=[
        "CREATE OR REPLACE TABLE EDX_COURSES USING TEMPLATE ( SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE( INFER_SCHEMA( LOCATION=>'@EDX_STAGE', FILE_FORMAT=>'inferSchema', IGNORE_CASE=>TRUE ) ) );",
        "COPY INTO EDX_COURSES FROM @EDX_STAGE FILE_FORMAT=(FORMAT_NAME='inferSchema') MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE;"
    ]
) }}
 
SELECT * FROM EDX_COURSES