{{ config(
    materialized='table',
    pre_hook=[
        "CREATE OR REPLACE TABLE COURSERA_COURSES USING TEMPLATE ( SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE( INFER_SCHEMA( LOCATION=>'@COURSERA_STAGE', FILE_FORMAT=>'inferSchema', IGNORE_CASE=>TRUE ) ) );",
        "COPY INTO COURSERA_COURSES FROM @COURSERA_STAGE FILE_FORMAT=(FORMAT_NAME='inferSchema') MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE;"
    ]
) }}

-- This SELECT statement is required by dbt. It simply returns the contents of the table.
SELECT * FROM COURSERA_COURSES
