{{ config(
    materialized='table',
    pre_hook=[
        "CREATE OR REPLACE TABLE UDEMY_COURSES USING TEMPLATE ( SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE( INFER_SCHEMA( LOCATION=>'@UDEMY_STAGE', FILE_FORMAT=>'inferSchema', IGNORE_CASE=>TRUE ) ) );",
        "COPY INTO UDEMY_COURSES FROM @UDEMY_STAGE FILE_FORMAT=(FORMAT_NAME='inferSchema') MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE;"
    ]
) }}
 
SELECT * FROM UDEMY_COURSES